#!/usr/bin/env bash
# reads lines from the file /etc/passwd and output only
# usernames, user id and home directory path in a single line
# While loops must be used

# Assign file descriptor to file for input fd #3 is file /etc/passwd
exec 3< /etc/passwd
while IFS= read -u 3 -r line
do
	echo "$line" | cut -d ':' -f 1,3,6
done
