#!/usr/bin/env bash
# This script displays "Best School" 10 times with an additional "Hi" the 9th time

i=0
while [ "$i" -ne 10 ]; do
	echo "Best School"
	((i+=1))
	if [ "$i" = 9 ]
	then
		echo "Hi"
	fi
done
