#!/usr/bin/env bash
# This script prints the numbers from 1 to 20 and prints
# "bad luck from China" after the number 4, "bad luck from Japan"
# after the number 9 and "bad luck from Italy" after the number 17

i=1
while [ "$i" -ne 21 ]; do
	echo "$i"
	case $i in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
	esac
	((i+=1))
done
