#!/usr/bin/env bash
# displays 12 hours and all the minutes for each hour

hour=0
while [ "$hour" -ne 13 ]; do
	echo "Hour: $hour"
	minute=1
	while [ "$minute" -ne 60 ]; do
		echo "$minute"
		((minute += 1))
	done
	((hour+=1))
done
