#!/usr/bin/env bash
# This script gives information about the school file. If it
#exists and some other properties if yes

i=school
if [ -f ./school ] || [ -d ./school ]
then
	echo "school file exists"
	if [ -s ./school ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f ./school ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
